FROM nginx:alpine

COPY libs/shared/ui/react/storybook-static /usr/share/nginx/html

COPY libs/shared/ui/react/nginx/storybook.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
